### ISSUE TITLE
有人看懂中文吗

### ISSUE THREAD

**Issue by Legolas970424** [pragmaticlearning/github-example#1424]
咱学到同一本书了哈哈哈

**Comment by CurbsideProphet** [comment]
emmm

**Comment by thj19980720** [comment]
sure

**Comment by zhy419** [comment]
6666

**Comment by HanochShi** [comment]
23333

**Comment by summer-ning** [comment]
6666

**Comment by Cl1p** [comment]
😄 💯 👍

**Comment by missmao97** [comment]
👍

**Comment by FutureStarfire** [comment]
666

**Comment by gitshaozhong** [comment]
这本《github入门》写的是真的垃圾！！！！！！！！！！翻译的真的是太垃圾了！！！！！！！！！！这作者真的是不负责任，自己都没读明白就用Google翻译出书，垃圾的一笔。读书读到生气我也是佩服这位作者！

**Comment by HanochShi** [comment]
> 这本《github入门》写的是真的垃圾！！！！！！！！！！翻译的真的是太垃圾了！！！！！！！！！！这作者真的是不负责任，自己都没读明白就用Google翻译出书，垃圾的一笔。读书读到生气我也是佩服这位作者！

对 我也觉得 翻译翻得是真的垃圾 整体看下来感觉还不如github上自带的guide

**Comment by Legolas970424** [comment]
> 这本《github入门》写的是真的垃圾！！！！！！！！！！翻译的真的是太垃圾了！！！！！！！！！！这作者真的是不负责任，自己都没读明白就用Google翻译出书，垃圾的一笔。读书读到生气我也是佩服这k

**Comment by Legolas970424** [comment]
> > 这本《github入门》写的是真的垃圾！！！！！！！！！！翻译的真的是太垃圾了！！！！！！！！！！这作者真的是不负责任，自己都没读明白就用Google翻译出书，垃圾的一笔。读书读到生气我也是佩服这位作者！
> 
> 对 我也觉得 翻译翻得是真的垃圾 整体看下来感觉还不如github上自带的guide

我看完了也觉得，这本书太烂了
